/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 c:\AIDev\AiDev_LLM\villaggio-terrace\src\assets\Female_Casual\public\Female_Casual.fbx.glb --types --output src/features/simPeople/components/SimPersonModel.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph, ThreeElements } from '@react-three/fiber'
import { useAnimations, useGLTF } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type GLTFAction = THREE.AnimationAction

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.SkinnedMesh
    mesh_0_1: THREE.SkinnedMesh
    mesh_0_2: THREE.SkinnedMesh
    mesh_0_3: THREE.SkinnedMesh
    mesh_0_4: THREE.SkinnedMesh
    mesh_0_5: THREE.SkinnedMesh
    mesh_0_6: THREE.SkinnedMesh
    mesh_0_7: THREE.SkinnedMesh
    mesh_0_8: THREE.SkinnedMesh
    mesh_0_9: THREE.SkinnedMesh
    mesh_0_10: THREE.SkinnedMesh
    mesh_0_11: THREE.SkinnedMesh
    mesh_0_12: THREE.SkinnedMesh
    mesh_0_13: THREE.SkinnedMesh
    mesh_0_14: THREE.SkinnedMesh
    mesh_0_15: THREE.SkinnedMesh
    mesh_0_16: THREE.SkinnedMesh
    mesh_0_17: THREE.SkinnedMesh
    mesh_0_18: THREE.SkinnedMesh
    mesh_0_19: THREE.SkinnedMesh
    mesh_0_20: THREE.SkinnedMesh
    mesh_0_21: THREE.SkinnedMesh
    mesh_0_22: THREE.SkinnedMesh
    mesh_0_23: THREE.SkinnedMesh
    mesh_0_24: THREE.SkinnedMesh
    mesh_0_25: THREE.SkinnedMesh
    mesh_0_26: THREE.SkinnedMesh
    mesh_0_27: THREE.SkinnedMesh
    mesh_0_28: THREE.SkinnedMesh
    mesh_0_29: THREE.SkinnedMesh
    mesh_0_30: THREE.SkinnedMesh
    mesh_0_31: THREE.SkinnedMesh
    mesh_0_32: THREE.SkinnedMesh
    mesh_0_33: THREE.SkinnedMesh
    mesh_0_34: THREE.SkinnedMesh
    mesh_0_35: THREE.SkinnedMesh
    mesh_0_36: THREE.SkinnedMesh
    mesh_0_37: THREE.SkinnedMesh
    mesh_0_38: THREE.SkinnedMesh
    mesh_0_39: THREE.SkinnedMesh
    mesh_0_40: THREE.SkinnedMesh
    mesh_0_41: THREE.SkinnedMesh
    mesh_0_42: THREE.SkinnedMesh
    mesh_0_43: THREE.SkinnedMesh
    mesh_0_44: THREE.SkinnedMesh
    mesh_0_45: THREE.SkinnedMesh
    mesh_0_46: THREE.SkinnedMesh
    mesh_0_47: THREE.SkinnedMesh
    mesh_0_48: THREE.SkinnedMesh
    mesh_0_49: THREE.SkinnedMesh
    mesh_0_50: THREE.SkinnedMesh
    mesh_0_51: THREE.SkinnedMesh
    mesh_0_52: THREE.SkinnedMesh
    mesh_0_53: THREE.SkinnedMesh
    mesh_0_54: THREE.SkinnedMesh
    mesh_0_55: THREE.SkinnedMesh
    mesh_0_56: THREE.SkinnedMesh
    mesh_0_57: THREE.SkinnedMesh
    mesh_0_58: THREE.SkinnedMesh
    mesh_0_59: THREE.SkinnedMesh
    mesh_0_60: THREE.SkinnedMesh
    mesh_0_61: THREE.SkinnedMesh
    mesh_0_62: THREE.SkinnedMesh
    mesh_0_63: THREE.SkinnedMesh
    mesh_0_64: THREE.SkinnedMesh
    mesh_0_65: THREE.SkinnedMesh
    mesh_0_66: THREE.SkinnedMesh
    mesh_0_67: THREE.SkinnedMesh
    mesh_0_68: THREE.SkinnedMesh
    mesh_0_69: THREE.SkinnedMesh
    mesh_0_70: THREE.SkinnedMesh
    mesh_0_71: THREE.SkinnedMesh
    mesh_0_72: THREE.SkinnedMesh
    mesh_0_73: THREE.SkinnedMesh
    mesh_0_74: THREE.SkinnedMesh
    mesh_0_75: THREE.SkinnedMesh
    mesh_0_76: THREE.SkinnedMesh
    mesh_0_77: THREE.SkinnedMesh
    mesh_0_78: THREE.SkinnedMesh
    mesh_0_79: THREE.SkinnedMesh
    mesh_0_80: THREE.SkinnedMesh
    mesh_0_81: THREE.SkinnedMesh
    mesh_0_82: THREE.SkinnedMesh
    mesh_0_83: THREE.SkinnedMesh
    mesh_0_84: THREE.SkinnedMesh
    mesh_0_85: THREE.SkinnedMesh
    mesh_0_86: THREE.SkinnedMesh
    mesh_0_87: THREE.SkinnedMesh
    mesh_0_88: THREE.SkinnedMesh
    mesh_0_89: THREE.SkinnedMesh
    mesh_0_90: THREE.SkinnedMesh
    mesh_0_91: THREE.SkinnedMesh
    mesh_0_92: THREE.SkinnedMesh
    mesh_0_93: THREE.SkinnedMesh
    mesh_0_94: THREE.SkinnedMesh
    mesh_0_95: THREE.SkinnedMesh
    mesh_0_96: THREE.SkinnedMesh
    mesh_0_97: THREE.SkinnedMesh
    mesh_0_98: THREE.SkinnedMesh
    mesh_0_99: THREE.SkinnedMesh
    mesh_0_100: THREE.SkinnedMesh
    mesh_0_101: THREE.SkinnedMesh
    mesh_0_102: THREE.SkinnedMesh
    mesh_0_103: THREE.SkinnedMesh
    mesh_0_104: THREE.SkinnedMesh
    mesh_0_105: THREE.SkinnedMesh
    mesh_0_106: THREE.SkinnedMesh
    mesh_0_107: THREE.SkinnedMesh
    mesh_0_108: THREE.SkinnedMesh
    mesh_0_109: THREE.SkinnedMesh
    mesh_0_110: THREE.SkinnedMesh
    mesh_0_111: THREE.SkinnedMesh
    mesh_0_112: THREE.SkinnedMesh
    mesh_0_113: THREE.SkinnedMesh
    mesh_0_114: THREE.SkinnedMesh
    mesh_0_115: THREE.SkinnedMesh
    mesh_0_116: THREE.SkinnedMesh
    mesh_0_117: THREE.SkinnedMesh
    mesh_0_118: THREE.SkinnedMesh
    mesh_0_119: THREE.SkinnedMesh
    mesh_0_120: THREE.SkinnedMesh
    mesh_0_121: THREE.SkinnedMesh
    mesh_0_122: THREE.SkinnedMesh
    mesh_0_123: THREE.SkinnedMesh
    mesh_0_124: THREE.SkinnedMesh
    mesh_0_125: THREE.SkinnedMesh
    mesh_0_126: THREE.SkinnedMesh
    mesh_0_127: THREE.SkinnedMesh
    mesh_0_128: THREE.SkinnedMesh
    mesh_0_129: THREE.SkinnedMesh
    mesh_0_130: THREE.SkinnedMesh
    mesh_0_131: THREE.SkinnedMesh
    mesh_0_132: THREE.SkinnedMesh
    mesh_0_133: THREE.SkinnedMesh
    mesh_0_134: THREE.SkinnedMesh
    mesh_0_135: THREE.SkinnedMesh
    mesh_0_136: THREE.SkinnedMesh
    mesh_0_137: THREE.SkinnedMesh
    mesh_0_138: THREE.SkinnedMesh
    mesh_0_139: THREE.SkinnedMesh
    mesh_0_140: THREE.SkinnedMesh
    mesh_0_141: THREE.SkinnedMesh
    mesh_0_142: THREE.SkinnedMesh
    mesh_0_143: THREE.SkinnedMesh
    mesh_0_144: THREE.SkinnedMesh
    mesh_0_145: THREE.SkinnedMesh
    mesh_0_146: THREE.SkinnedMesh
    mesh_0_147: THREE.SkinnedMesh
    mesh_0_148: THREE.SkinnedMesh
    mesh_0_149: THREE.SkinnedMesh
    mesh_0_150: THREE.SkinnedMesh
    Bone: THREE.Bone
  }
  materials: {
    Shirt: THREE.MeshStandardMaterial
    Skin: THREE.MeshStandardMaterial
    Pants: THREE.MeshStandardMaterial
    Shoes: THREE.MeshStandardMaterial
    Socks: THREE.MeshStandardMaterial
    HairBase: THREE.MeshStandardMaterial
    Hair: THREE.MeshStandardMaterial
    Eyes: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model({ tint = '#ffffff', skinTint = '#ffffff', ...props }: ThreeElements['group'] & { tint?: string, skinTint?: string }) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF(`${(import.meta as any).env.BASE_URL}Female_Casual.fbx.glb`)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  // Apply tints to materials for variety
  React.useMemo(() => {
    if (materials.Shirt) materials.Shirt.color.set(tint)
    if (materials.Skin) materials.Skin.color.set(skinTint)
  }, [materials, tint, skinTint])

  React.useEffect(() => {
    // Play idle by default if it exists
    const idleAction = actions['Idle'] || Object.values(actions)[0]
    if (idleAction) {
      idleAction.reset().fadeIn(0.5).play()
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <primitive object={nodes.Bone} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <skinnedMesh geometry={nodes.mesh_0.geometry} material={materials.Shirt} skeleton={nodes.mesh_0.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_1.geometry} material={materials.Skin} skeleton={nodes.mesh_0_1.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_2.geometry} material={materials.Pants} skeleton={nodes.mesh_0_2.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_3.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_3.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_4.geometry} material={materials.Pants} skeleton={nodes.mesh_0_4.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_5.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_5.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_6.geometry} material={materials.Pants} skeleton={nodes.mesh_0_6.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_7.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_7.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_8.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_8.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_9.geometry} material={materials.Pants} skeleton={nodes.mesh_0_9.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_10.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_10.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_11.geometry} material={materials.Pants} skeleton={nodes.mesh_0_11.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_12.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_12.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_13.geometry} material={materials.Pants} skeleton={nodes.mesh_0_13.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_14.geometry} material={materials.Socks} skeleton={nodes.mesh_0_14.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_15.geometry} material={materials.Pants} skeleton={nodes.mesh_0_15.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_16.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_16.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_17.geometry} material={materials.Socks} skeleton={nodes.mesh_0_17.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_18.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_18.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_19.geometry} material={materials.Pants} skeleton={nodes.mesh_0_19.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_20.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_20.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_21.geometry} material={materials.Pants} skeleton={nodes.mesh_0_21.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_22.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_22.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_23.geometry} material={materials.Pants} skeleton={nodes.mesh_0_23.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_24.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_24.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_25.geometry} material={materials.Pants} skeleton={nodes.mesh_0_25.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_26.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_26.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_27.geometry} material={materials.Skin} skeleton={nodes.mesh_0_27.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_28.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_28.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_29.geometry} material={materials.Pants} skeleton={nodes.mesh_0_29.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_30.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_30.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_31.geometry} material={materials.Pants} skeleton={nodes.mesh_0_31.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_32.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_32.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_33.geometry} material={materials.Pants} skeleton={nodes.mesh_0_33.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_34.geometry} material={materials.Socks} skeleton={nodes.mesh_0_34.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_35.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_35.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_36.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_36.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_37.geometry} material={materials.Skin} skeleton={nodes.mesh_0_37.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_38.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_38.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_39.geometry} material={materials.Pants} skeleton={nodes.mesh_0_39.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_40.geometry} material={materials.Socks} skeleton={nodes.mesh_0_40.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_41.geometry} material={materials.Pants} skeleton={nodes.mesh_0_41.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_42.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_42.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_43.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_43.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_44.geometry} material={materials.Pants} skeleton={nodes.mesh_0_44.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_45.geometry} material={materials.Skin} skeleton={nodes.mesh_0_45.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_46.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_46.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_47.geometry} material={materials.Pants} skeleton={nodes.mesh_0_47.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_48.geometry} material={materials.Skin} skeleton={nodes.mesh_0_48.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_49.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_49.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_50.geometry} material={materials.Skin} skeleton={nodes.mesh_0_50.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_51.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_51.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_52.geometry} material={materials.Skin} skeleton={nodes.mesh_0_52.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_53.geometry} material={materials.Pants} skeleton={nodes.mesh_0_53.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_54.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_54.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_55.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_55.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_56.geometry} material={materials.Skin} skeleton={nodes.mesh_0_56.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_57.geometry} material={materials.Pants} skeleton={nodes.mesh_0_57.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_58.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_58.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_59.geometry} material={materials.Skin} skeleton={nodes.mesh_0_59.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_60.geometry} material={materials.HairBase} skeleton={nodes.mesh_0_60.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_61.geometry} material={materials.Skin} skeleton={nodes.mesh_0_61.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_62.geometry} material={materials.HairBase} skeleton={nodes.mesh_0_62.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_63.geometry} material={materials.Skin} skeleton={nodes.mesh_0_63.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_64.geometry} material={materials.HairBase} skeleton={nodes.mesh_0_64.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_65.geometry} material={materials.Skin} skeleton={nodes.mesh_0_65.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_66.geometry} material={materials.HairBase} skeleton={nodes.mesh_0_66.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_67.geometry} material={materials.Skin} skeleton={nodes.mesh_0_67.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_68.geometry} material={materials.HairBase} skeleton={nodes.mesh_0_68.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_69.geometry} material={materials.Skin} skeleton={nodes.mesh_0_69.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_70.geometry} material={materials.HairBase} skeleton={nodes.mesh_0_70.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_71.geometry} material={materials.Skin} skeleton={nodes.mesh_0_71.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_72.geometry} material={materials.HairBase} skeleton={nodes.mesh_0_72.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_73.geometry} material={materials.Skin} skeleton={nodes.mesh_0_73.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_74.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_74.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_75.geometry} material={materials.Skin} skeleton={nodes.mesh_0_75.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_76.geometry} material={materials.Pants} skeleton={nodes.mesh_0_76.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_77.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_77.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_78.geometry} material={materials.Pants} skeleton={nodes.mesh_0_78.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_79.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_79.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_80.geometry} material={materials.Pants} skeleton={nodes.mesh_0_80.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_81.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_81.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_82.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_82.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_83.geometry} material={materials.Pants} skeleton={nodes.mesh_0_83.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_84.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_84.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_85.geometry} material={materials.Pants} skeleton={nodes.mesh_0_85.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_86.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_86.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_87.geometry} material={materials.Pants} skeleton={nodes.mesh_0_87.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_88.geometry} material={materials.Socks} skeleton={nodes.mesh_0_88.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_89.geometry} material={materials.Pants} skeleton={nodes.mesh_0_89.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_90.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_90.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_91.geometry} material={materials.Socks} skeleton={nodes.mesh_0_91.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_92.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_92.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_93.geometry} material={materials.Pants} skeleton={nodes.mesh_0_93.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_94.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_94.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_95.geometry} material={materials.Pants} skeleton={nodes.mesh_0_95.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_96.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_96.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_97.geometry} material={materials.Pants} skeleton={nodes.mesh_0_97.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_98.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_98.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_99.geometry} material={materials.Pants} skeleton={nodes.mesh_0_99.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_100.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_100.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_101.geometry} material={materials.Skin} skeleton={nodes.mesh_0_101.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_102.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_102.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_103.geometry} material={materials.Pants} skeleton={nodes.mesh_0_103.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_104.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_104.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_105.geometry} material={materials.Pants} skeleton={nodes.mesh_0_105.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_106.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_106.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_107.geometry} material={materials.Pants} skeleton={nodes.mesh_0_107.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_108.geometry} material={materials.Socks} skeleton={nodes.mesh_0_108.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_109.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_109.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_110.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_110.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_111.geometry} material={materials.Skin} skeleton={nodes.mesh_0_111.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_112.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_112.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_113.geometry} material={materials.Pants} skeleton={nodes.mesh_0_113.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_114.geometry} material={materials.Socks} skeleton={nodes.mesh_0_114.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_115.geometry} material={materials.Pants} skeleton={nodes.mesh_0_115.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_116.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_116.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_117.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_117.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_118.geometry} material={materials.Pants} skeleton={nodes.mesh_0_118.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_119.geometry} material={materials.Skin} skeleton={nodes.mesh_0_119.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_120.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_120.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_121.geometry} material={materials.Pants} skeleton={nodes.mesh_0_121.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_122.geometry} material={materials.Skin} skeleton={nodes.mesh_0_122.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_123.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_123.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_124.geometry} material={materials.Skin} skeleton={nodes.mesh_0_124.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_125.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_125.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_126.geometry} material={materials.Skin} skeleton={nodes.mesh_0_126.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_127.geometry} material={materials.Pants} skeleton={nodes.mesh_0_127.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_128.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_128.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_129.geometry} material={materials.Shoes} skeleton={nodes.mesh_0_129.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_130.geometry} material={materials.Skin} skeleton={nodes.mesh_0_130.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_131.geometry} material={materials.Pants} skeleton={nodes.mesh_0_131.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_132.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_132.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_133.geometry} material={materials.Skin} skeleton={nodes.mesh_0_133.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_134.geometry} material={materials.HairBase} skeleton={nodes.mesh_0_134.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_135.geometry} material={materials.Skin} skeleton={nodes.mesh_0_135.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_136.geometry} material={materials.HairBase} skeleton={nodes.mesh_0_136.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_137.geometry} material={materials.Skin} skeleton={nodes.mesh_0_137.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_138.geometry} material={materials.HairBase} skeleton={nodes.mesh_0_138.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_139.geometry} material={materials.Skin} skeleton={nodes.mesh_0_139.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_140.geometry} material={materials.HairBase} skeleton={nodes.mesh_0_140.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_141.geometry} material={materials.Skin} skeleton={nodes.mesh_0_141.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_142.geometry} material={materials.HairBase} skeleton={nodes.mesh_0_142.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_143.geometry} material={materials.Skin} skeleton={nodes.mesh_0_143.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_144.geometry} material={materials.HairBase} skeleton={nodes.mesh_0_144.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_145.geometry} material={materials.Skin} skeleton={nodes.mesh_0_145.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_146.geometry} material={materials.HairBase} skeleton={nodes.mesh_0_146.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_147.geometry} material={materials.Skin} skeleton={nodes.mesh_0_147.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_148.geometry} material={materials.Shirt} skeleton={nodes.mesh_0_148.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_149.geometry} material={materials.Hair} skeleton={nodes.mesh_0_149.skeleton} />
        <skinnedMesh geometry={nodes.mesh_0_150.geometry} material={materials.Eyes} skeleton={nodes.mesh_0_150.skeleton} />
      </group>
    </group>
  )
}

// Preload cannot use import.meta at module scope in all bundlers;
// the Model component itself handles loading via useGLTF.
