// Theme core: Only expose the palette and mode for direct consumption.
// All other theme-related definitions (sizing, components, etc.)
// are considered legacy and will be removed.

export const themeTokens = {
  "--theme-main-toolbar-button-icon-size":
    theme.sizing.components.mainToolbar.button.iconSize,
  "--theme-main-toolbar-button-stroke-width":
    theme.sizing.components.mainToolbar.button.strokeWidth,
  "--theme-main-toolbar-button-shadow":
    theme.sizing.components.mainToolbar.button.shadow,
  "--theme-main-toolbar-button-active-scale":
    theme.sizing.components.mainToolbar.button.activeScale,
  "--theme-main-toolbar-button-idle-opacity":
    theme.sizing.components.mainToolbar.button.idleOpacity,
  "--theme-main-toolbar-button-active-background":
    theme.sizing.components.mainToolbar.button.activeBackground,
  "--theme-main-toolbar-button-active-foreground":
    theme.sizing.components.mainToolbar.button.activeForeground,
  "--theme-main-toolbar-button-idle-foreground":
    theme.sizing.components.mainToolbar.button.idleForeground,
  "--theme-main-toolbar-button-hover-background":
    theme.sizing.components.mainToolbar.button.hoverBackground,
  "--theme-main-toolbar-button-hover-foreground":
    theme.sizing.components.mainToolbar.button.hoverForeground,
  "--theme-main-toolbar-separator-width":
    theme.sizing.components.mainToolbar.separator.width,
  "--theme-main-toolbar-separator-height":
    theme.sizing.components.mainToolbar.separator.height,
  "--theme-main-toolbar-separator-color":
    theme.sizing.components.mainToolbar.separator.color,
  "--theme-main-toolbar-separator-opacity":
    theme.sizing.components.mainToolbar.separator.opacity,
  "--theme-main-toolbar-resource-gap":
    theme.sizing.components.mainToolbar.resourceBadge.gap,
  "--theme-main-toolbar-resource-padding-x":
    theme.sizing.components.mainToolbar.resourceBadge.paddingX,
  "--theme-main-toolbar-resource-padding-y":
    theme.sizing.components.mainToolbar.resourceBadge.paddingY,
  "--theme-main-toolbar-resource-icon-size":
    theme.sizing.components.mainToolbar.resourceBadge.iconSize,
  "--theme-main-toolbar-resource-text-size":
    theme.sizing.components.mainToolbar.resourceBadge.textSize,
  "--theme-main-toolbar-money-padding-x":
    theme.sizing.components.mainToolbar.moneyIndicator.paddingX,
  "--theme-main-toolbar-money-padding-y":
    theme.sizing.components.mainToolbar.moneyIndicator.paddingY,
  "--theme-main-toolbar-money-gap":
    theme.sizing.components.mainToolbar.moneyIndicator.gap,
  "--theme-main-toolbar-money-icon-size":
    theme.sizing.components.mainToolbar.moneyIndicator.iconSize,
  "--theme-main-toolbar-money-radius":
    theme.sizing.components.mainToolbar.moneyIndicator.radius,
  "--theme-main-toolbar-money-border":
    theme.sizing.components.mainToolbar.moneyIndicator.border,
  "--theme-main-toolbar-money-shadow":
    theme.sizing.components.mainToolbar.moneyIndicator.shadow,
  "--theme-main-toolbar-money-background":
    theme.sizing.components.mainToolbar.moneyIndicator.background,
  "--theme-main-toolbar-money-foreground":
    theme.sizing.components.mainToolbar.moneyIndicator.foreground,
  "--theme-main-toolbar-money-hover-scale":
    theme.sizing.components.mainToolbar.moneyIndicator.hoverScale,
  "--theme-main-toolbar-menu-padding":
    theme.sizing.components.mainToolbar.menu.padding,
  "--theme-main-toolbar-menu-min-width":
    theme.sizing.components.mainToolbar.menu.minWidth,
  "--theme-main-toolbar-menu-radius":
    theme.sizing.components.mainToolbar.menu.radius,
  "--theme-main-toolbar-menu-background":
    theme.sizing.components.mainToolbar.menu.background,
  "--theme-main-toolbar-menu-border":
    theme.sizing.components.mainToolbar.menu.border,
  "--theme-main-toolbar-menu-shadow":
    theme.sizing.components.mainToolbar.menu.shadow,
  "--theme-main-toolbar-menu-backdrop":
    theme.sizing.components.mainToolbar.menu.backdrop,
  "--theme-main-toolbar-menu-z-index":
    theme.sizing.components.mainToolbar.menu.zIndex,
  "--theme-main-toolbar-menu-position-offset":
    theme.sizing.components.mainToolbar.menu.positionOffset,
  "--theme-main-toolbar-menu-header-padding-x":
    theme.sizing.components.mainToolbar.menu.headerPaddingX,
  "--theme-main-toolbar-menu-header-padding-y":
    theme.sizing.components.mainToolbar.menu.headerPaddingY,
  "--theme-main-toolbar-menu-header-margin-bottom":
    theme.sizing.components.mainToolbar.menu.headerMarginBottom,
  "--theme-main-toolbar-menu-header-border-bottom":
    theme.sizing.components.mainToolbar.menu.headerBorderBottom,
  "--theme-main-toolbar-menu-header-text-size":
    theme.sizing.components.mainToolbar.menu.headerTextSize,
  "--theme-main-toolbar-menu-header-font-family":
    theme.sizing.components.mainToolbar.menu.headerFontFamily,
  "--theme-main-toolbar-menu-header-font-weight":
    theme.sizing.components.mainToolbar.menu.headerFontWeight,
  "--theme-main-toolbar-menu-header-text-transform":
    theme.sizing.components.mainToolbar.menu.headerTextTransform,
  "--theme-main-toolbar-menu-header-tracking":
    theme.sizing.components.mainToolbar.menu.headerTracking,
  "--theme-main-toolbar-menu-header-foreground":
    theme.sizing.components.mainToolbar.menu.headerForeground,
  "--theme-main-toolbar-menu-row-padding-x":
    theme.sizing.components.mainToolbar.menu.rowPaddingX,
  "--theme-main-toolbar-menu-row-padding-y":
    theme.sizing.components.mainToolbar.menu.rowPaddingY,
  "--theme-main-toolbar-menu-row-gap":
    theme.sizing.components.mainToolbar.menu.rowGap,
  "--theme-main-toolbar-menu-row-radius":
    theme.sizing.components.mainToolbar.menu.rowRadius,
  "--theme-main-toolbar-menu-row-text-size":
    theme.sizing.components.mainToolbar.menu.rowTextSize,
  "--theme-main-toolbar-menu-row-font-weight":
    theme.sizing.components.mainToolbar.menu.rowFontWeight,
  "--theme-main-toolbar-menu-row-transition":
    theme.sizing.components.mainToolbar.menu.rowTransition,
  "--theme-main-toolbar-menu-row-idle-foreground":
    theme.sizing.components.mainToolbar.menu.rowIdleForeground,
  "--theme-main-toolbar-menu-row-idle-background":
    theme.sizing.components.mainToolbar.menu.rowIdleBackground,
  "--theme-main-toolbar-menu-row-hover-foreground":
    theme.sizing.components.mainToolbar.menu.rowHoverForeground,
  "--theme-main-toolbar-menu-row-hover-background":
    theme.sizing.components.mainToolbar.menu.rowHoverBackground,
  "--theme-main-toolbar-menu-row-active-foreground":
    theme.sizing.components.mainToolbar.menu.rowActiveForeground,
  "--theme-main-toolbar-menu-row-active-background":
    theme.sizing.components.mainToolbar.menu.rowActiveBackground,
  "--theme-main-toolbar-menu-row-icon-size":
    theme.sizing.components.mainToolbar.menu.rowIconSize,
  "--theme-main-toolbar-menu-row-icon-stroke-width":
    theme.sizing.components.mainToolbar.menu.rowIconStrokeWidth,
  "--theme-main-toolbar-menu-check-icon-size":
    theme.sizing.components.mainToolbar.menu.checkIconSize,
  "--theme-main-toolbar-menu-check-icon-foreground":
    theme.sizing.components.mainToolbar.menu.checkIconForeground,
};

export const getThemeTokens = (mode: ThemeMode = "dark"): ThemeTokens =>
  themeTokens[mode];
