/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.SkinnedMesh
    mesh_0_1: THREE.SkinnedMesh
    mesh_0_2: THREE.SkinnedMesh
    mesh_0_3: THREE.SkinnedMesh
    mesh_0_4: THREE.SkinnedMesh
    mesh_0_5: THREE.SkinnedMesh
    mesh_0_6: THREE.SkinnedMesh
    mesh_0_7: THREE.SkinnedMesh
    mesh_0_8: THREE.SkinnedMesh
    mesh_0_9: THREE.SkinnedMesh
    mesh_0_10: THREE.SkinnedMesh
    mesh_0_11: THREE.SkinnedMesh
    mesh_0_12: THREE.SkinnedMesh
    mesh_0_13: THREE.SkinnedMesh
    mesh_0_14: THREE.SkinnedMesh
    mesh_0_15: THREE.SkinnedMesh
    mesh_0_16: THREE.SkinnedMesh
    mesh_0_17: THREE.SkinnedMesh
    mesh_0_18: THREE.SkinnedMesh
    mesh_0_19: THREE.SkinnedMesh
    mesh_0_20: THREE.SkinnedMesh
    mesh_0_21: THREE.SkinnedMesh
    mesh_0_22: THREE.SkinnedMesh
    mesh_0_23: THREE.SkinnedMesh
    mesh_0_24: THREE.SkinnedMesh
    mesh_0_25: THREE.SkinnedMesh
    mesh_0_26: THREE.SkinnedMesh
    mesh_0_27: THREE.SkinnedMesh
    mesh_0_28: THREE.SkinnedMesh
    mesh_0_29: THREE.SkinnedMesh
    mesh_0_30: THREE.SkinnedMesh
    mesh_0_31: THREE.SkinnedMesh
    mesh_0_32: THREE.SkinnedMesh
    mesh_0_33: THREE.SkinnedMesh
    mesh_0_34: THREE.SkinnedMesh
    mesh_0_35: THREE.SkinnedMesh
    mesh_0_36: THREE.SkinnedMesh
    mesh_0_37: THREE.SkinnedMesh
    mesh_0_38: THREE.SkinnedMesh
    mesh_0_39: THREE.SkinnedMesh
    mesh_0_40: THREE.SkinnedMesh
    mesh_0_41: THREE.SkinnedMesh
    mesh_0_42: THREE.SkinnedMesh
    mesh_0_43: THREE.SkinnedMesh
    mesh_0_44: THREE.SkinnedMesh
    mesh_0_45: THREE.SkinnedMesh
    mesh_0_46: THREE.SkinnedMesh
    mesh_0_47: THREE.SkinnedMesh
    mesh_0_48: THREE.SkinnedMesh
    mesh_0_49: THREE.SkinnedMesh
    mesh_0_50: THREE.SkinnedMesh
    mesh_0_51: THREE.SkinnedMesh
    mesh_0_52: THREE.SkinnedMesh
    mesh_0_53: THREE.SkinnedMesh
    mesh_0_54: THREE.SkinnedMesh
    mesh_0_55: THREE.SkinnedMesh
    mesh_0_56: THREE.SkinnedMesh
    mesh_0_57: THREE.SkinnedMesh
    mesh_0_58: THREE.SkinnedMesh
    mesh_0_59: THREE.SkinnedMesh
    mesh_0_60: THREE.SkinnedMesh
    mesh_0_61: THREE.SkinnedMesh
    mesh_0_62: THREE.SkinnedMesh
    mesh_0_63: THREE.SkinnedMesh
    mesh_0_64: THREE.SkinnedMesh
    mesh_0_65: THREE.SkinnedMesh
    mesh_0_66: THREE.SkinnedMesh
    mesh_0_67: THREE.SkinnedMesh
    mesh_0_68: THREE.SkinnedMesh
    mesh_0_69: THREE.SkinnedMesh
    mesh_0_70: THREE.SkinnedMesh
    mesh_0_71: THREE.SkinnedMesh
    mesh_0_72: THREE.SkinnedMesh
    mesh_0_73: THREE.SkinnedMesh
    mesh_0_74: THREE.SkinnedMesh
    mesh_0_75: THREE.SkinnedMesh
    mesh_0_76: THREE.SkinnedMesh
    mesh_0_77: THREE.SkinnedMesh
    mesh_0_78: THREE.SkinnedMesh
    mesh_0_79: THREE.SkinnedMesh
    mesh_0_80: THREE.SkinnedMesh
    mesh_0_81: THREE.SkinnedMesh
    mesh_0_82: THREE.SkinnedMesh
    mesh_0_83: THREE.SkinnedMesh
    mesh_0_84: THREE.SkinnedMesh
    mesh_0_85: THREE.SkinnedMesh
    mesh_0_86: THREE.SkinnedMesh
    mesh_0_87: THREE.SkinnedMesh
    mesh_0_88: THREE.SkinnedMesh
    mesh_0_89: THREE.SkinnedMesh
    mesh_0_90: THREE.SkinnedMesh
    mesh_0_91: THREE.SkinnedMesh
    mesh_0_92: THREE.SkinnedMesh
    mesh_0_93: THREE.SkinnedMesh
    mesh_0_94: THREE.SkinnedMesh
    mesh_0_95: THREE.SkinnedMesh
    mesh_0_96: THREE.SkinnedMesh
    mesh_0_97: THREE.SkinnedMesh
    mesh_0_98: THREE.SkinnedMesh
    mesh_0_99: THREE.SkinnedMesh
    mesh_0_100: THREE.SkinnedMesh
    mesh_0_101: THREE.SkinnedMesh
    mesh_0_102: THREE.SkinnedMesh
    mesh_0_103: THREE.SkinnedMesh
    mesh_0_104: THREE.SkinnedMesh
    mesh_0_105: THREE.SkinnedMesh
    mesh_0_106: THREE.SkinnedMesh
    mesh_0_107: THREE.SkinnedMesh
    mesh_0_108: THREE.SkinnedMesh
    mesh_0_109: THREE.SkinnedMesh
    mesh_0_110: THREE.SkinnedMesh
    mesh_0_111: THREE.SkinnedMesh
    mesh_0_112: THREE.SkinnedMesh
    mesh_0_113: THREE.SkinnedMesh
    mesh_0_114: THREE.SkinnedMesh
    mesh_0_115: THREE.SkinnedMesh
    mesh_0_116: THREE.SkinnedMesh
    mesh_0_117: THREE.SkinnedMesh
    mesh_0_118: THREE.SkinnedMesh
    mesh_0_119: THREE.SkinnedMesh
    mesh_0_120: THREE.SkinnedMesh
    mesh_0_121: THREE.SkinnedMesh
    mesh_0_122: THREE.SkinnedMesh
    mesh_0_123: THREE.SkinnedMesh
    mesh_0_124: THREE.SkinnedMesh
    mesh_0_125: THREE.SkinnedMesh
    mesh_0_126: THREE.SkinnedMesh
    mesh_0_127: THREE.SkinnedMesh
    mesh_0_128: THREE.SkinnedMesh
    mesh_0_129: THREE.SkinnedMesh
    mesh_0_130: THREE.SkinnedMesh
    mesh_0_131: THREE.SkinnedMesh
    mesh_0_132: THREE.SkinnedMesh
    mesh_0_133: THREE.SkinnedMesh
    mesh_0_134: THREE.SkinnedMesh
    mesh_0_135: THREE.SkinnedMesh
    mesh_0_136: THREE.SkinnedMesh
    mesh_0_137: THREE.SkinnedMesh
    mesh_0_138: THREE.SkinnedMesh
    mesh_0_139: THREE.SkinnedMesh
    mesh_0_140: THREE.SkinnedMesh
    mesh_0_141: THREE.SkinnedMesh
    mesh_0_142: THREE.SkinnedMesh
    mesh_0_143: THREE.SkinnedMesh
    mesh_0_144: THREE.SkinnedMesh
    mesh_0_145: THREE.SkinnedMesh
    mesh_0_146: THREE.SkinnedMesh
    mesh_0_147: THREE.SkinnedMesh
    mesh_0_148: THREE.SkinnedMesh
    mesh_0_149: THREE.SkinnedMesh
    mesh_0_150: THREE.SkinnedMesh
    Bone: THREE.Bone
  }
  materials: {
    Shirt: THREE.MeshStandardMaterial
    Skin: THREE.MeshStandardMaterial
    Pants: THREE.MeshStandardMaterial
    Shoes: THREE.MeshStandardMaterial
    Socks: THREE.MeshStandardMaterial
    HairBase: THREE.MeshStandardMaterial
    Hair: THREE.MeshStandardMaterial
    Eyes: THREE.MeshStandardMaterial
  }
}

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/Female_Casual.fbx.glb') as GLTFResult
  const instances = useMemo(
    () => ({
      Mesh: nodes.mesh_0,
      Mesh1: nodes.mesh_0_1,
      Mesh2: nodes.mesh_0_2,
      Mesh3: nodes.mesh_0_3,
      Mesh4: nodes.mesh_0_4,
      Mesh5: nodes.mesh_0_5,
      Mesh6: nodes.mesh_0_6,
      Mesh7: nodes.mesh_0_7,
      Mesh8: nodes.mesh_0_8,
      Mesh9: nodes.mesh_0_9,
      Mesh10: nodes.mesh_0_10,
      Mesh11: nodes.mesh_0_11,
      Mesh12: nodes.mesh_0_12,
      Mesh13: nodes.mesh_0_13,
      Mesh14: nodes.mesh_0_14,
      Mesh15: nodes.mesh_0_15,
      Mesh16: nodes.mesh_0_16,
      Mesh17: nodes.mesh_0_17,
      Mesh18: nodes.mesh_0_18,
      Mesh19: nodes.mesh_0_19,
      Mesh20: nodes.mesh_0_20,
      Mesh21: nodes.mesh_0_21,
      Mesh22: nodes.mesh_0_22,
      Mesh23: nodes.mesh_0_23,
      Mesh24: nodes.mesh_0_24,
      Mesh25: nodes.mesh_0_25,
      Mesh26: nodes.mesh_0_26,
      Mesh27: nodes.mesh_0_27,
      Mesh28: nodes.mesh_0_28,
      Mesh29: nodes.mesh_0_29,
      Mesh30: nodes.mesh_0_30,
      Mesh31: nodes.mesh_0_31,
      Mesh32: nodes.mesh_0_32,
      Mesh33: nodes.mesh_0_33,
      Mesh34: nodes.mesh_0_34,
      Mesh35: nodes.mesh_0_35,
      Mesh36: nodes.mesh_0_36,
      Mesh37: nodes.mesh_0_37,
      Mesh38: nodes.mesh_0_38,
      Mesh39: nodes.mesh_0_39,
      Mesh40: nodes.mesh_0_40,
      Mesh41: nodes.mesh_0_41,
      Mesh42: nodes.mesh_0_42,
      Mesh43: nodes.mesh_0_43,
      Mesh44: nodes.mesh_0_44,
      Mesh45: nodes.mesh_0_45,
      Mesh46: nodes.mesh_0_46,
      Mesh47: nodes.mesh_0_47,
      Mesh48: nodes.mesh_0_48,
      Mesh49: nodes.mesh_0_49,
      Mesh50: nodes.mesh_0_50,
      Mesh51: nodes.mesh_0_51,
      Mesh52: nodes.mesh_0_52,
      Mesh53: nodes.mesh_0_53,
      Mesh54: nodes.mesh_0_54,
      Mesh55: nodes.mesh_0_55,
      Mesh56: nodes.mesh_0_56,
      Mesh57: nodes.mesh_0_57,
      Mesh58: nodes.mesh_0_58,
      Mesh59: nodes.mesh_0_59,
      Mesh60: nodes.mesh_0_60,
      Mesh61: nodes.mesh_0_61,
      Mesh62: nodes.mesh_0_62,
      Mesh63: nodes.mesh_0_63,
      Mesh64: nodes.mesh_0_64,
      Mesh65: nodes.mesh_0_65,
      Mesh66: nodes.mesh_0_66,
      Mesh67: nodes.mesh_0_67,
      Mesh68: nodes.mesh_0_68,
      Mesh69: nodes.mesh_0_69,
      Mesh70: nodes.mesh_0_70,
      Mesh71: nodes.mesh_0_71,
      Mesh72: nodes.mesh_0_72,
      Mesh73: nodes.mesh_0_73,
      Mesh74: nodes.mesh_0_74,
      Mesh75: nodes.mesh_0_75,
      Mesh76: nodes.mesh_0_76,
      Mesh77: nodes.mesh_0_77,
      Mesh78: nodes.mesh_0_78,
      Mesh79: nodes.mesh_0_79,
      Mesh80: nodes.mesh_0_80,
      Mesh81: nodes.mesh_0_81,
      Mesh82: nodes.mesh_0_82,
      Mesh83: nodes.mesh_0_83,
      Mesh84: nodes.mesh_0_84,
      Mesh85: nodes.mesh_0_85,
      Mesh86: nodes.mesh_0_86,
      Mesh87: nodes.mesh_0_87,
      Mesh88: nodes.mesh_0_88,
      Mesh89: nodes.mesh_0_89,
      Mesh90: nodes.mesh_0_90,
      Mesh91: nodes.mesh_0_91,
      Mesh92: nodes.mesh_0_92,
      Mesh93: nodes.mesh_0_93,
      Mesh94: nodes.mesh_0_94,
      Mesh95: nodes.mesh_0_95,
      Mesh96: nodes.mesh_0_96,
      Mesh97: nodes.mesh_0_97,
      Mesh98: nodes.mesh_0_98,
      Mesh99: nodes.mesh_0_99,
      Mesh100: nodes.mesh_0_100,
      Mesh101: nodes.mesh_0_101,
      Mesh102: nodes.mesh_0_102,
      Mesh103: nodes.mesh_0_103,
      Mesh104: nodes.mesh_0_104,
      Mesh105: nodes.mesh_0_105,
      Mesh106: nodes.mesh_0_106,
      Mesh107: nodes.mesh_0_107,
      Mesh108: nodes.mesh_0_108,
      Mesh109: nodes.mesh_0_109,
      Mesh110: nodes.mesh_0_110,
      Mesh111: nodes.mesh_0_111,
      Mesh112: nodes.mesh_0_112,
      Mesh113: nodes.mesh_0_113,
      Mesh114: nodes.mesh_0_114,
      Mesh115: nodes.mesh_0_115,
      Mesh116: nodes.mesh_0_116,
      Mesh117: nodes.mesh_0_117,
      Mesh118: nodes.mesh_0_118,
      Mesh119: nodes.mesh_0_119,
      Mesh120: nodes.mesh_0_120,
      Mesh121: nodes.mesh_0_121,
      Mesh122: nodes.mesh_0_122,
      Mesh123: nodes.mesh_0_123,
      Mesh124: nodes.mesh_0_124,
      Mesh125: nodes.mesh_0_125,
      Mesh126: nodes.mesh_0_126,
      Mesh127: nodes.mesh_0_127,
      Mesh128: nodes.mesh_0_128,
      Mesh129: nodes.mesh_0_129,
      Mesh130: nodes.mesh_0_130,
      Mesh131: nodes.mesh_0_131,
      Mesh132: nodes.mesh_0_132,
      Mesh133: nodes.mesh_0_133,
      Mesh134: nodes.mesh_0_134,
      Mesh135: nodes.mesh_0_135,
      Mesh136: nodes.mesh_0_136,
      Mesh137: nodes.mesh_0_137,
      Mesh138: nodes.mesh_0_138,
      Mesh139: nodes.mesh_0_139,
      Mesh140: nodes.mesh_0_140,
      Mesh141: nodes.mesh_0_141,
      Mesh142: nodes.mesh_0_142,
      Mesh143: nodes.mesh_0_143,
      Mesh144: nodes.mesh_0_144,
      Mesh145: nodes.mesh_0_145,
      Mesh146: nodes.mesh_0_146,
      Mesh147: nodes.mesh_0_147,
      Mesh148: nodes.mesh_0_148,
      Mesh149: nodes.mesh_0_149,
      Mesh150: nodes.mesh_0_150,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <group>
        <group>
          <group name="HumanArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Bone} />
          </group>
          <group name="Female" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <instances.Mesh name="mesh_0" />
            <instances.Mesh1 name="mesh_0_1" />
            <instances.Mesh2 name="mesh_0_2" />
            <instances.Mesh3 name="mesh_0_3" />
            <instances.Mesh4 name="mesh_0_4" />
            <instances.Mesh5 name="mesh_0_5" />
            <instances.Mesh6 name="mesh_0_6" />
            <instances.Mesh7 name="mesh_0_7" />
            <instances.Mesh8 name="mesh_0_8" />
            <instances.Mesh9 name="mesh_0_9" />
            <instances.Mesh10 name="mesh_0_10" />
            <instances.Mesh11 name="mesh_0_11" />
            <instances.Mesh12 name="mesh_0_12" />
            <instances.Mesh13 name="mesh_0_13" />
            <instances.Mesh14 name="mesh_0_14" />
            <instances.Mesh15 name="mesh_0_15" />
            <instances.Mesh16 name="mesh_0_16" />
            <instances.Mesh17 name="mesh_0_17" />
            <instances.Mesh18 name="mesh_0_18" />
            <instances.Mesh19 name="mesh_0_19" />
            <instances.Mesh20 name="mesh_0_20" />
            <instances.Mesh21 name="mesh_0_21" />
            <instances.Mesh22 name="mesh_0_22" />
            <instances.Mesh23 name="mesh_0_23" />
            <instances.Mesh24 name="mesh_0_24" />
            <instances.Mesh25 name="mesh_0_25" />
            <instances.Mesh26 name="mesh_0_26" />
            <instances.Mesh27 name="mesh_0_27" />
            <instances.Mesh28 name="mesh_0_28" />
            <instances.Mesh29 name="mesh_0_29" />
            <instances.Mesh30 name="mesh_0_30" />
            <instances.Mesh31 name="mesh_0_31" />
            <instances.Mesh32 name="mesh_0_32" />
            <instances.Mesh33 name="mesh_0_33" />
            <instances.Mesh34 name="mesh_0_34" />
            <instances.Mesh35 name="mesh_0_35" />
            <instances.Mesh36 name="mesh_0_36" />
            <instances.Mesh37 name="mesh_0_37" />
            <instances.Mesh38 name="mesh_0_38" />
            <instances.Mesh39 name="mesh_0_39" />
            <instances.Mesh40 name="mesh_0_40" />
            <instances.Mesh41 name="mesh_0_41" />
            <instances.Mesh42 name="mesh_0_42" />
            <instances.Mesh43 name="mesh_0_43" />
            <instances.Mesh44 name="mesh_0_44" />
            <instances.Mesh45 name="mesh_0_45" />
            <instances.Mesh46 name="mesh_0_46" />
            <instances.Mesh47 name="mesh_0_47" />
            <instances.Mesh48 name="mesh_0_48" />
            <instances.Mesh49 name="mesh_0_49" />
            <instances.Mesh50 name="mesh_0_50" />
            <instances.Mesh51 name="mesh_0_51" />
            <instances.Mesh52 name="mesh_0_52" />
            <instances.Mesh53 name="mesh_0_53" />
            <instances.Mesh54 name="mesh_0_54" />
            <instances.Mesh55 name="mesh_0_55" />
            <instances.Mesh56 name="mesh_0_56" />
            <instances.Mesh57 name="mesh_0_57" />
            <instances.Mesh58 name="mesh_0_58" />
            <instances.Mesh59 name="mesh_0_59" />
            <instances.Mesh60 name="mesh_0_60" />
            <instances.Mesh61 name="mesh_0_61" />
            <instances.Mesh62 name="mesh_0_62" />
            <instances.Mesh63 name="mesh_0_63" />
            <instances.Mesh64 name="mesh_0_64" />
            <instances.Mesh65 name="mesh_0_65" />
            <instances.Mesh66 name="mesh_0_66" />
            <instances.Mesh67 name="mesh_0_67" />
            <instances.Mesh68 name="mesh_0_68" />
            <instances.Mesh69 name="mesh_0_69" />
            <instances.Mesh70 name="mesh_0_70" />
            <instances.Mesh71 name="mesh_0_71" />
            <instances.Mesh72 name="mesh_0_72" />
            <instances.Mesh73 name="mesh_0_73" />
            <instances.Mesh74 name="mesh_0_74" />
            <instances.Mesh75 name="mesh_0_75" />
            <instances.Mesh76 name="mesh_0_76" />
            <instances.Mesh77 name="mesh_0_77" />
            <instances.Mesh78 name="mesh_0_78" />
            <instances.Mesh79 name="mesh_0_79" />
            <instances.Mesh80 name="mesh_0_80" />
            <instances.Mesh81 name="mesh_0_81" />
            <instances.Mesh82 name="mesh_0_82" />
            <instances.Mesh83 name="mesh_0_83" />
            <instances.Mesh84 name="mesh_0_84" />
            <instances.Mesh85 name="mesh_0_85" />
            <instances.Mesh86 name="mesh_0_86" />
            <instances.Mesh87 name="mesh_0_87" />
            <instances.Mesh88 name="mesh_0_88" />
            <instances.Mesh89 name="mesh_0_89" />
            <instances.Mesh90 name="mesh_0_90" />
            <instances.Mesh91 name="mesh_0_91" />
            <instances.Mesh92 name="mesh_0_92" />
            <instances.Mesh93 name="mesh_0_93" />
            <instances.Mesh94 name="mesh_0_94" />
            <instances.Mesh95 name="mesh_0_95" />
            <instances.Mesh96 name="mesh_0_96" />
            <instances.Mesh97 name="mesh_0_97" />
            <instances.Mesh98 name="mesh_0_98" />
            <instances.Mesh99 name="mesh_0_99" />
            <instances.Mesh100 name="mesh_0_100" />
            <instances.Mesh101 name="mesh_0_101" />
            <instances.Mesh102 name="mesh_0_102" />
            <instances.Mesh103 name="mesh_0_103" />
            <instances.Mesh104 name="mesh_0_104" />
            <instances.Mesh105 name="mesh_0_105" />
            <instances.Mesh106 name="mesh_0_106" />
            <instances.Mesh107 name="mesh_0_107" />
            <instances.Mesh108 name="mesh_0_108" />
            <instances.Mesh109 name="mesh_0_109" />
            <instances.Mesh110 name="mesh_0_110" />
            <instances.Mesh111 name="mesh_0_111" />
            <instances.Mesh112 name="mesh_0_112" />
            <instances.Mesh113 name="mesh_0_113" />
            <instances.Mesh114 name="mesh_0_114" />
            <instances.Mesh115 name="mesh_0_115" />
            <instances.Mesh116 name="mesh_0_116" />
            <instances.Mesh117 name="mesh_0_117" />
            <instances.Mesh118 name="mesh_0_118" />
            <instances.Mesh119 name="mesh_0_119" />
            <instances.Mesh120 name="mesh_0_120" />
            <instances.Mesh121 name="mesh_0_121" />
            <instances.Mesh122 name="mesh_0_122" />
            <instances.Mesh123 name="mesh_0_123" />
            <instances.Mesh124 name="mesh_0_124" />
            <instances.Mesh125 name="mesh_0_125" />
            <instances.Mesh126 name="mesh_0_126" />
            <instances.Mesh127 name="mesh_0_127" />
            <instances.Mesh128 name="mesh_0_128" />
            <instances.Mesh129 name="mesh_0_129" />
            <instances.Mesh130 name="mesh_0_130" />
            <instances.Mesh131 name="mesh_0_131" />
            <instances.Mesh132 name="mesh_0_132" />
            <instances.Mesh133 name="mesh_0_133" />
            <instances.Mesh134 name="mesh_0_134" />
            <instances.Mesh135 name="mesh_0_135" />
            <instances.Mesh136 name="mesh_0_136" />
            <instances.Mesh137 name="mesh_0_137" />
            <instances.Mesh138 name="mesh_0_138" />
            <instances.Mesh139 name="mesh_0_139" />
            <instances.Mesh140 name="mesh_0_140" />
            <instances.Mesh141 name="mesh_0_141" />
            <instances.Mesh142 name="mesh_0_142" />
            <instances.Mesh143 name="mesh_0_143" />
            <instances.Mesh144 name="mesh_0_144" />
            <instances.Mesh145 name="mesh_0_145" />
            <instances.Mesh146 name="mesh_0_146" />
            <instances.Mesh147 name="mesh_0_147" />
            <instances.Mesh148 name="mesh_0_148" />
            <instances.Mesh149 name="mesh_0_149" />
            <instances.Mesh150 name="mesh_0_150" />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Female_Casual.fbx.glb')
